### ISSUE TITLE
can't send to private irc server

### ISSUE THREAD

**Issue by mago0** [portertech/carrier-pigeon#3]
I have a private irc server (inspircd) that I can't seem to get cp to hit. I can send to our freenode room without issue but when pointed to our internal server, I invoke it and it pauses briefly before returning with no output.

Here's my test script:

```
require 'rubygems'
require 'carrier-pigeon'

irc_uri = "irc://testbot:thepass!$!$@irc1.oursite.com:6667/#private"
message = "testing"

CarrierPigeon.send(
    :uri => irc_uri, 
    :message => message, 
    :ssl => true, 
    :join => true
)
```

I've changed most of the details above but our password does have the !$ characters in it. Not sure if this could cause issues.

**Comment by portertech** [comment]
Interesting, carrier pigeon seems to work w/ most IRC servers, perhaps it does have to do w/ your choice of password :) Perhaps we should work through each lib step in irb to see if this is the case? Any chance you could provision another user & password w/o the use of those characters?

**Comment by mago0** [comment]
Changing the password did not fix it. Is there a freenode channel we can work together on?

**Comment by portertech** [comment]
@mago0 I'm on freenode, "portertech" :)

**Comment by portertech** [comment]
Does your irc server debug log provide any hints?

**Comment by guzmanbraso** [comment]
At the end, issue is not inspire, same problem happens in ircu.

Issue is some irc servers require client to answer first ping before consider them registered on the server.
Carrier pigeon does not support that, and therefore when join and privmsg arrive, server rejects them with "Register first", which as CP does not read socket, do not even know it didn't work.

Going to submit a patch in a few minutes...

**Comment by portertech** [comment]
@guzmanbraso Thanks for attacking this one, do you intended to add an option like :register_first => boolean? Block on read.

**Comment by guzmanbraso** [comment]
Uops, submitted patch before reading your comment, give me a minute, will resubmit.

**Comment by guzmanbraso** [comment]
There you have :) thanks!

**Comment by guzmanbraso** [comment]
By the way, my experience with ruby is none, please review it :)

**Comment by portertech** [comment]
Looks good, have you tested? Could you create a pull request?

**Comment by guzmanbraso** [comment]
Yes, I've tested both true & false option on it, I tested using puppet irc module which just calls carrier pigeon for puppet reports.

Will create pull right now

**Comment by portertech** [comment]
I will do a few quick tests myself, now that I've merged your fix in, and then roll a new release.

**Comment by portertech** [comment]
Fixed in #5

**Comment by portertech** [comment]
@mago0 Please `gem install carrier-pigeon -v 0.5.0` for :register_first :)

Register (ping reply) prior to joining or messaging a channel (required for some private servers)

 CarrierPigeon.send(
   :uri => "irc://nick:password@irc.domain.com:6667/#channel",
   :message => "cooooo, coo coo",
   :register_first => true,
   :join => true
 )

**Comment by mostlyobvious** [comment]
That doesn't work for me on inspircd since the server does not send PING after connect. It seems that client should wait after sending NICK/USER/PASS.

It worked when I've added 200ms sleep after https://github.com/portertech/carrier-pigeon/blob/master/lib/carrier-pigeon.rb#L24.

Below are server debug logs from unsuccessful and successful message sends respectively:

```
Thu Mar 28 13:30:19 2013: HandleEvent for Listensocket 10.0.0.8:6667 nfd=6
Thu Mar 28 13:30:19 2013: classbase::+ @0x7f7b8800c820
Thu Mar 28 13:30:19 2013: New UUID for user: 349AAAABI
Thu Mar 28 13:30:19 2013: classbase::+ @0x7f7b8800c968
Thu Mar 28 13:30:19 2013: New user fd: 6
Thu Mar 28 13:30:19 2013: Setting connect class for UID 349AAAABI
Thu Mar 28 13:30:19 2013: Checking unnamed-0
Thu Mar 28 13:30:19 2013: New file descriptor: 6
Thu Mar 28 13:30:19 2013: Resolver::Resolver
Thu Mar 28 13:30:19 2013: DNSRequest::SendRequests
Thu Mar 28 13:30:19 2013: Sent OK
Thu Mar 28 13:30:19 2013: DNS request id 58720
Thu Mar 28 13:30:19 2013: AddResolverClass 0x7f7b88001960
Thu Mar 28 13:30:19 2013: Handle DNS event
Thu Mar 28 13:30:19 2013: Result id 124256
Thu Mar 28 13:30:21 2013: QuitUser: 349AAAABI=monitoring 'Quit: quit'
Thu Mar 28 13:30:21 2013: Remove file descriptor: 6
Thu Mar 28 13:30:21 2013: Setting connect class for UID 349AAAABI
Thu Mar 28 13:30:21 2013: Checking unnamed-0
Thu Mar 28 13:30:22 2013: Deleting 9LocalUser @0x7f7b8800c820
Thu Mar 28 13:30:22 2013: classbase::-13UserIOHandler @0x7f7b8800c968
Thu Mar 28 13:30:22 2013: classbase::-9LocalUser @0x7f7b8800c820
Thu Mar 28 13:30:22 2013: classbase::~ @0x7f7b8800c968
Thu Mar 28 13:30:22 2013: classbase::~ @0x7f7b8800c820
```

```
Thu Mar 28 13:32:12 2013: HandleEvent for Listensocket 10.0.0.8:6667 nfd=6
Thu Mar 28 13:32:12 2013: classbase::+ @0x7f7b8800cb70
Thu Mar 28 13:32:12 2013: New UUID for user: 349AAAABL
Thu Mar 28 13:32:12 2013: classbase::+ @0x7f7b8800ccb8
Thu Mar 28 13:32:12 2013: New user fd: 6
Thu Mar 28 13:32:12 2013: Setting connect class for UID 349AAAABL
Thu Mar 28 13:32:12 2013: Checking unnamed-0
Thu Mar 28 13:32:12 2013: BanCache: Negative hit for 10.254.0.202
Thu Mar 28 13:32:12 2013: New file descriptor: 6
Thu Mar 28 13:32:12 2013: Resolver::Resolver
Thu Mar 28 13:32:12 2013: DNSRequest::SendRequests
Thu Mar 28 13:32:12 2013: Sent OK
Thu Mar 28 13:32:12 2013: DNS request id 49238
Thu Mar 28 13:32:12 2013: AddResolverClass 0x7f7b88003b40
Thu Mar 28 13:32:12 2013: Handle DNS event
Thu Mar 28 13:32:12 2013: Result id 114774
Thu Mar 28 13:32:13 2013: Setting connect class for UID 349AAAABL
Thu Mar 28 13:32:13 2013: Checking unnamed-0
Thu Mar 28 13:32:13 2013: CONNECT: Client connecting on port 6667: monitoring!monitoring@10.254.0.202 [10.254.0.202] [monitoring]
Thu Mar 28 13:32:13 2013: BanCache: Adding NEGATIVE hit for 10.254.0.202
Thu Mar 28 13:32:14 2013: QuitUser: 349AAAABL=monitoring 'Quit: quit'
Thu Mar 28 13:32:14 2013: Remove file descriptor: 6
Thu Mar 28 13:32:14 2013: QUIT: Client exiting: monitoring!monitoring@10.254.0.202 [Quit: quit] (10.254.0.202)
Thu Mar 28 13:32:14 2013: classbase::+ @0x7fff7b6ef360
Thu Mar 28 13:32:14 2013: classbase::~ @0x7fff7b6ef360
Thu Mar 28 13:32:15 2013: Deleting 9LocalUser @0x7f7b8800cb70
Thu Mar 28 13:32:15 2013: classbase::-13UserIOHandler @0x7f7b8800ccb8
Thu Mar 28 13:32:15 2013: classbase::-9LocalUser @0x7f7b8800cb70
Thu Mar 28 13:32:15 2013: classbase::~ @0x7f7b8800ccb8
Thu Mar 28 13:32:15 2013: classbase::~ @0x7f7b8800cb70
```

**Comment by portertech** [comment]
@pawelpacana Perhaps we need register_wait, which would take a sleep time in ms?

**Comment by mostlyobvious** [comment]
@portertech Not sure if it's the right thing. Github irc notification works like this: https://github.com/github/github-services/blob/master/lib/services/irc.rb#L55-L60

And that works for my private inspircd instance as well as for freenode.

**Comment by portertech** [comment]
Ah, neat! Would you like to put together a PR?

**Comment by mostlyobvious** [comment]
@portertech I've made a PR in #11
